name: Deploy Azure App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar pasta de build
        run: mkdir build

      - name: Copiar arquivos do site para pasta de build
        run: cp index.html style.css script.js -t build/

      - name: Compactar arquivos
        run: zip -r site.zip ./build

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-sabor-caseiro
          package: site.zip
