name: Deploy Azure App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Zipar os arquivos
        run: |
          zip site.zip index.html style.css script.js

      - name: Deploy via publish profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-sabor-caseiro
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: site.zip
