name: Deploy Azure App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar site.zip com arquivos direto da raiz
        run: |
          mkdir temp-site
          cp index.html style.css script.js temp-site/
          cd temp-site
          zip -r ../site.zip .
          cd ..
          rm -rf temp-site

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-sabor-caseiro
          package: site.zip
