name: Deploy Azure App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar estrutura de pastas para o site
        run: |
          mkdir -p site
          cp index.html style.css script.js site/

      - name: Compactar em site.zip com pasta 'site'
        run: zip -r site.zip site

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-sabor-caseiro
          package: site.zip
